name: MGBRoleAward
version: '${project.version}'
main: vip.floatationdevice.mgbroleaward.MGBRoleAward
api-version: 1.13
depend: [ MGBridge ]
commands:
  mgbroleaward:
    description: The main command of MGBRoleAward
permissions:
  mgbroleaward.reload:
    description: The permission to use the reload command
    default: op
  mgbroleaward.check:
    description: The permission to use the check command
    default: op
